[versions]
aeron = "1.48.2"
agrona = "2.2.2"
byteBuddy = "1.17.5"
checkstyle = "10.25.0"
commons-codec = "1.15"
commons-lang3 = "3.8.1"
hamcrest = "3.0"
hdrHistogram = "2.2.2"
httpcore = "4.4.14"
jmh = "1.37"
json = "20250517"
junit = "5.13.1"
junit4 = "4.13.2"
mockito = "5.18.0"
plexus = "3.3.0"
sbe = "1.35.4"
shadow = "8.3.6"
versions = "0.52.0"

[libraries]
agrona = { group = "org.agrona", name = "agrona", version.ref = "agrona" }
aeron-client = { group = "io.aeron", name = "aeron-client", version.ref = "aeron" }
aeron-archive = { group = "io.aeron", name = "aeron-archive", version.ref = "aeron" }
byteBuddy = { group = "net.bytebuddy", name = "byte-buddy", version.ref = "byteBuddy" }
byteBuddy-agent = { group = "net.bytebuddy", name = "byte-buddy-agent", version.ref = "byteBuddy" }
commons-codec = { group = "commons-codec", name = "commons-codec", version.ref = "commons-codec" }
commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang3" }
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
hdrHistogram = { group = "org.hdrhistogram", name = "HdrHistogram", version.ref = "hdrHistogram" }
httpcore = { group = "org.apache.httpcomponents", name = "httpcore", version.ref = "httpcore" }
jmh-core = { group = "org.openjdk.jmh", name = "jmh-core", version.ref = "jmh" }
jmh-generator-annprocess = { group = "org.openjdk.jmh", name = "jmh-generator-annprocess", version.ref = "jmh" }
json = { group = "org.json", name = "json", version.ref = "json" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
mockito = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
plexus-utils = { group = "org.codehaus.plexus", name = "plexus-utils", version.ref = "plexus" }
sbe = { group = "uk.co.real-logic", name = "sbe-tool", version.ref = "sbe" }

[plugins]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions" }
